### ISSUE TITLE
Instant crash with PHP8

### ISSUE THREAD

**Issue by nipos** [danopia/php-ircd#6]
socket_create() doesn't create a Resource anymore as of PHP version 8,instead it returns a Socket.
See docs here: https://www.php.net/manual/en/function.socket-create.php
This causes a problem with the while(is_resource($sock)) queue in server.php line 152 that makes the script immediately end.
I made a quick and dirty fix by replacing the line with while(true) but that doesn't detect when the socket closes.
At least the server does now work again but maybe you'll find a better solution.

**Comment by JosunLP** [comment]
https://github.com/danopia/php-ircd/pull/7

**Comment by nipos** [comment]
It works much better with your fix,thank you.
But there are still some spl_object_id() functions missing in connection_handler.php.
The script crashes for example when you request the Whois for a user.

**Comment by JosunLP** [comment]
i will take a look at it as fast as i can (unfortunately I don't have the time right now)

**Comment by JosunLP** [comment]
https://github.com/danopia/php-ircd/pull/8

**Comment by JosunLP** [comment]
@nipos im not sure if @danopia will take a look at my PR, the code should work now.

**Comment by danopia** [comment]
If there's consensus that the PR helps the code run, I'll merge it, but overall this repo is effectively abandoned and I'll likely 'archive' it in the near future

**Comment by JosunLP** [comment]
I updated the rest of the requested changes by @nipos , it should work fine. Tested with hexchat

**Comment by nipos** [comment]
It works quite good now,except that it crashes everytime a client disconnects.
This is caused by a spl_object_id() still missing in server.php line 117.
I fixed that locally at my server and now it's working fine.
Tested with KDE Konversation, Haiku Vision and KiwiIRC.

**Comment by JosunLP** [comment]
Will fix this in a few minutes. Strage that my IDE didn't called me out on it 🤔. But im Happy to provide a solution ^^

**Comment by JosunLP** [comment]
commit is done @danopia @nipos

**Comment by JosunLP** [comment]
@danopia could you close this issue?

**Comment by danopia** [comment]
Sure. I've also created a README.md to the repository to help provide some context on the history.
